apiVersion: v2
name: vm-example-chart
version: 0.1.9-beta.1
dependencies:
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 8.3.6
    condition: grafana.enabled
  - name: victoria-logs-single
    repository: https://victoriametrics.github.io/helm-charts
    version: 0.3.6
    condition: victoria-logs-single.enabled
  - name: victoria-metrics-agent
    repository: https://victoriametrics.github.io/helm-charts
    version: 0.10.4
    condition: victoria-metrics-agent.enabled
  - name: victoria-metrics-cluster
    repository: https://victoriametrics.github.io/helm-charts
    version: 0.11.14
    condition: victoria-metrics-cluster.enabled
  - name: prometheus-node-exporter
    repository: https://prometheus-community.github.io/helm-charts
    version: 4.32.0
    condition: prometheus-node-exporter.enabled
  - name: kube-state-metrics
    repository: https://prometheus-community.github.io/helm-charts
    version: 5.18.1
    condition: prometheus-node-exporter.enabled
  - name: telegraf
    repository: https://helm.influxdata.com
    version: 1.8.53
    condition: telegraf.enabled