name: Release Charts

on:
  push:
    branches:
      - main
      - master
    paths:
      - "**/Chart.yaml"

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.9.8
            
      - name: Check if the chart version is not a release version
        id: check
        run: |
          cat charts/vm-example-chart/Chart.yaml | yq e '.version | select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))'
          count=$(cat charts/vm-example-chart/Chart.yaml | yq e '.version | select(test("^[0-9]+\\.[0-9]+\\.[0-9]+$"))' | wc -l)
          if [[ $count != 1 ]]; then
            echo  "release_check=false" >> $GITHUB_OUTPUT
          else
            echo  "release_check=true" >> $GITHUB_OUTPUT
          fi

      - if : ${{ steps.check.outputs.release_check == 'true' }}
        name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - if : ${{ steps.check.outputs.release_check == 'true' }}
        name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - if : ${{ steps.check.outputs.release_check == 'true' }}
        name: Run chart-releaser
        uses: neilkuan/chart-releaser-action@v1.6.2
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"