name: PR Check Commit Chart.yaml

on:
  pull_request:
    paths:
      - '*/**/**'
      - '!.github/workflows/**'
      - '!README.md'
      - '!.mergify.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.validate.outputs.conclusion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
      - name: Check commit Chart.yaml
        id: validate
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          touch change.txt
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file" >> change.txt
          done
          grep Chart.yaml change.txt && echo "Nice Job"
          if [[ $? != 0 ]];then
              echo "Please commit Chart.yaml"
              echo "conclusion=failure" >> $GITHUB_OUTPUT
          fi
          echo "conclusion=success" >> $GITHUB_OUTPUT

  update:
    name: Update status job
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Update status check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONCLUSION: ${{ needs.validate.outputs.conclusion }}
          PR_BRANCH: ${{ github.head_ref || github.ref_name }}
        run: |
            if [[ $CONCLUSION == "failure" ]]; then
                gh api \
                --method POST \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                /repos/${GITHUB_REPOSITORY}/statuses/${GITHUB_SHA} \
                 -f "state=failure" -f "description=The build failure!"
            else
                gh api \
                --method POST \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                /repos/${GITHUB_REPOSITORY}/statuses/${GITHUB_SHA} \
                 -f "state=success" -f "description=The build succeeded!"
            fi  