name: PR Check Commit Chart.yaml

on:
  merge_group:
  pull_request:
    paths:
      - '*/**/**'
      - '!.github/workflows/**'
      - '!README.md'
      - '!.mergify.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
      - name: Check commit Chart.yaml
        id: validate
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          touch change.txt
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file" >> change.txt
          done
          grep Chart.yaml change.txt && echo "Nice Job"
          if [[ $? != 0 ]];then
              echo "Please commit Chart.yaml"
              echo "conclusion=failure" >> $GITHUB_OUTPUT
          fi
          echo "conclusion=success" >> $GITHUB_OUTPUT
      - name: Update status check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONCLUSION: ${{ steps.validate.outputs.conclusion }}
          PR_BRANCH: ${{ github.head_ref || github.ref_name }}
        run: |
            echo "CONCLUSION: $CONCLUSION"
            echo "PR_BRANCH: $PR_BRANCH"
            echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
            echo "GITHUB_SHA: $GITHUB_SHA"

            if [[ $CONCLUSION == "failure" ]]; then
                echo "The PR Check Commit Chart.yaml in_progress!"
                gh api -X POST -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -f 'name=The PR Check Commit Chart.yaml' \
                -f 'head_sha=${{ github.event.pull_request.head.sha }}' \
                -f 'status=in_progress' \
                -f 'output[title]=The PR Check Commit Chart.yaml in_progress !!!' \
                /repos/${{ github.repository }}/check-runs
            else
                echo "The PR Check Commit Chart.yaml completed!"
                 gh api -X POST -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                -f 'name=The PR Check Commit Chart.yaml' \
                -f 'head_sha=${{ github.event.pull_request.head.sha }}' \
                -f 'status=completed' \
                -f 'output[title]=The PR Check Commit Chart.yaml completed !!!' \
                /repos/${{ github.repository }}/check-runs
            fi